export const menuItems = {
  food: [
    {
      Name: "Shack Burger",
      Color: "background-color: #38b70e",
      Mods: ["Single", "Double", "Triple"],
      Price: 7.29,
      Ingredients: [
        "Bun",
        "Butter",
        "Lettuce",
        "Tomato",
        "Shack Sauce",
        "Onions",
        "Cheese",
        "Burger Patty",
      ],
    },
    {
      Name: "Cheese Burger",
      Color: "#38b70e",
      Mods: ["Single", "Double", "Triple"],
      Price: 7.19,
      Ingredients: ["Bun", "Butter", "Cheese", "Burger Patty"],
    },
    {
      Name: "Grilled Cheese",
      Color: "#38b70e",
      Mods: false,
      Price: 5.49,
      Ingredients: ["Bun", "Butter", "Cheese"],
    },
    {
      Name: "Burger",
      Color: "#38b70e",
      Mods: ["Single", "Double", "Triple"],
      Price: 6.79,
      Ingredients: ["Bun", "Butter", "Burger Patty"],
    },
    {
      Name: "Smoke Shake",
      Color: "#38b70e",
      Mods: ["Single", "Double", "Triple"],
      Price: 8.89,
      Ingredients: [
        "Bun",
        "Butter",
        "Cheese",
        "Shake Sauce",
        "Cherry Peppers",
        "Burger Patty",
      ],
    },
    {
      Name: "Shroom Burger",
      Color: "#38b70e",
      Mods: false,
      Price: 8.99,
      Ingredients: [
        "Bun",
        "Butter",
        "Cheese",
        "Shake Sauce",
        "Cherry Peppers",
        "Shroom Patty",
      ],
    },
    {
      Name: "Shack Stack",
      Color: "#38b70e",
      Mods: false,
      Price: 12.69,
      Ingredients: [
        "Bun",
        "Butter",
        "Lettuce",
        "Tomato",
        "Shack Sauce",
        "Onions",
        "Cheese",
        "Burger Patty",
        "Shroom Patty",
      ],
    },
    {
      Name: "Bacon Avocado",
      Color: "#38b70e",
      Mods: false,
      Price: 10.09,
      Ingredients: ["Bun", "Butter", "Burger Patty", "Bacon", "Avacado"],
    },
    {
      Name: "Bacon Avocado Chicken",
      Color: "#38b70e",
      Mods: false,
      Price: 10.99,
      Ingredients: ["Bun", "Butter", "Chicken Patty", "Bacon", "Avacado"],
    },
    {
      Name: "Bacon Cheese Burger",
      Color: "#38b70e",
      Mods: false,
      Price: 8.99,
      Ingredients: ["Bun", "Butter", "Burger Patty", "Bacon", "Cheese"],
    },
    {
      Name: "Fries",
      Color: "#38b70e",
      Mods: false,
      Price: 3.99,
      Ingredients: ["Fries"],
    },
    {
      Name: "Cheese Fries",
      Color: "#38b70e",
      Mods: false,
      Price: 4.99,
      Ingredients: ["Fries", "Cheese"],
    },
    {
      Name: "Bacon Cheese Fries",
      Color: "#38b70e",
      Mods: false,
      Price: 6.49,
      Ingredients: ["Fries", "Cheese"],
    },
    {
      Name: "Hot Dog",
      Color: "#17bce1",
      Mods: false,
      Price: 4.49,
      Ingredients: ["Hot Dog Bun", "Hot Dog"],
    },
    {
      Name: "Chicken Shack",
      Color: "#17bce1",
      Mods: false,
      Price: 8.89,
      Ingredients: [
        "Bun",
        "Chicken Patty",
        "Pickle Chips",
        "Lettuce",
        "Herb Mayo",
      ],
    },
    {
      Name: "Bites 10 PC",
      Color: "Yellow",
      Mods: false,
      Price: 8.49,
      Ingredients: ["Chicken Nugget"],
    },
    {
      Name: "Bites 6 PC",
      Color: "Yellow",
      Mods: false,
      Price: 5.59,
      Ingredients: ["Chicken Nugget"],
    },
    {
      Name: "Hot Ones Burger",
      Color: "Red",
      Mods: false,
      Price: 8.99,
      Ingredients: ["Bun", "Burger Patty", "Cheese", "Bacon", "Hot Ones Sauce"],
    },
    {
      Name: "Hot Ones Chicken",
      Color: "Red",
      Mods: false,
      Price: 9.59,
      Ingredients: [
        "Bun",
        "Chicken Patty",
        "Cheese",
        "Bacon",
        "Hot Ones Sauce",
      ],
    },
    {
      Name: "Hot Ones Cheese Fries",
      Color: "Red",
      Mods: false,
      Price: 5.39,
      Ingredients: ["Cheese", "Hot Ones Flakes", "Fries"],
    },
    {
      Name: "Hot Ones Bacon Cheese Fries",
      Color: "Red",
      Mods: false,
      Price: 6.59,
      Ingredients: ["Cheese", "Bacon", "Hot Ones Flakes", "Fries"],
    },
  ],
  custard: [
    {
      Name: "Cookies & Cream",
      Color: "Pink",
      Mods: false,
      Price: 5.49,
      Ingredients: ["Vanilla Custard", "Oreo Flakes"],
    },
    {
      Name: "Chocolate Shake",
      Color: "Pink",
      Mods: false,
      Price: 5.49,
      Ingredients: ["Chocolate Custard"],
    },
    {
      Name: "Chocolate Milk & Cookies Shake",
      Color: "Pink",
      Mods: false,
      Price: 6.49,
      Ingredients: ["Chocolate Custard", "Whippedd Cream", "Oreo Flakes"],
    },
    {
      Name: "Strawberry Shake",
      Color: "Pink",
      Mods: false,
      Price: 5.49,
      Ingredients: ["Vanilla Custard", "Strawberry Flavour"],
    },
    {
      Name: "Vanilla Shake",
      Color: "Pink",
      Mods: false,
      Price: 5.49,
      Ingredients: ["Vanilla Custard"],
    },
    {
      Name: "Christmas Cookie Shake",
      Color: "Pink",
      Mods: false,
      Price: 6.49,
      Ingredients: [
        "Vanilla Custard",
        "Peppermint Flavour",
        "Christmas Sprinkles",
        "Whipped Cream",
      ],
    },
    {
      Name: "Chocolate Peppermint",
      Color: "Pink",
      Mods: false,
      Price: 6.49,
      Ingredients: [
        "Chocolate Custard",
        "Peppermint Flavour",
        "Peppermint Skprinkles",
        "Whipped Cream",
      ],
    },
  ],
  hot_addons: [
    {
      Name: "Bacon",
      Color: "Light Green",
      Mods: false,
      Price: 1.99,
      Ingredients: ["Bacon"],
    },
    {
      Name: "Salt And Pepper",
      Color: "Light Green",
      Mods: false,
      Price: 0,
      Ingredients: ["Salt", "Pepper"],
    },
    {
      Name: "Cheese",
      Color: "Light Green",
      Mods: false,
      Price: 0,
      Ingredients: ["Cheese"],
    },
    {
      Name: "Salt",
      Color: "Orange",
      Mods: false,
      Price: 0,
      Ingredients: ["Salt"],
    },
    {
      Name: "Pepper",
      Color: "Orange",
      Mods: false,
      Price: 0,
      Ingredients: ["Pepper"],
    },
    {
      Name: "Shack Sauce",
      Color: "Pink",
      Mods: false,
      Price: 0,
      Ingredients: ["Mayo", "Ketchup"],
    },
    {
      Name: "Lettuce",
      Color: "Pink",
      Mods: false,
      Price: 0,
      Ingredients: ["Lettuce"],
    },
    {
      Name: "Tomato",
      Color: "Pink",
      Mods: false,
      Price: 0,
      Ingredients: ["Lettuce"],
    },
    {
      Name: "Onion",
      Color: "Pink",
      Mods: false,
      Price: 0,
      Ingredients: ["Onion"],
    },
    {
      Name: "Pickles",
      Color: "Pink",
      Mods: false,
      Price: 0,
      Ingredients: ["Pickles"],
    },
    {
      Name: "Cherry Peppers",
      Color: "Pink",
      Mods: false,
      Price: 0.5,
      Ingredients: ["Cherry Peppers"],
    },
    {
      Name: "Herb Mayo",
      Color: "Orange",
      Mods: false,
      Price: 0,
      Ingredients: ["Mayo"],
    },
    {
      Name: "Fried Chicken Patty",
      Color: "Light Green",
      Mods: false,
      Price: 3,
      Ingredients: ["Chicken", "Breading"],
    },
    {
      Name: "Lettuce Wrap",
      Color: "Orange",
      Mods: false,
      Price: 0,
      Ingredients: ["Chicken", "Breading"],
    },
    {
      Name: "Shallots",
      Color: "Light Green",
      Mods: false,
      Price: 1,
      Ingredients: ["Onion", "Breading"],
    },
    {
      Name: "Shroom Patty",
      Color: "Light Green",
      Mods: false,
      Price: 4,
      Ingredients: ["Mushroom", "Breading"],
    },
    {
      Name: "Gluten Freen Bun",
      Color: "Light Green",
      Mods: false,
      Price: 1,
      Ingredients: ["Gluten Free Bun"],
    },
  ],
};

export default menuItems;
